### ISSUE TITLE
No such file or directory: 'cmd.exe' on Windows

### ISSUE THREAD

**Issue by DrManhattanHack** [ShutdownRepo/Exegol#109]
Good morning friends, currently I have a problem to run exegol, I made the installation of docker on windows meditante wsl2, all good in the installation, I can run exegol, but when using functions such as info, start, install, etc, I get an error called FileNotFoundError: [Errno 2] No such file or directory: 'cmd.exe', I appreciate your help.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/102842533/181780350-d835344f-c067-4b81-a25b-4e70d2cfd7f3.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/102842533/181780418-e486a50a-57ed-4710-8b56-308176b04d5a.png">
<img width="524" alt="image" src="https://user-images.githubusercontent.com/102842533/181780501-982fc0ae-5e94-4554-96ef-2c8dd1da8c2b.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/102842533/181780561-41411bda-7c99-4d5c-933e-5812f0e663cd.png">

**Comment by ShutdownRepo** [comment]
Hmm that's weird, thanks for pointing it out. @Dramelac will probably be the best suited to help on that matter :wink:

**Comment by Dramelac** [comment]
Hello,
First, thank you for the feedback!
Indeed it is a rather unusual behavior. Normally windows executables can be run from a WSL context, here cmd.exe (cf. Windows docs: https://docs.microsoft.com/en-us/windows/wsl/filesystems#run-windows-tools-from-linux).
Have you modified the PATH or any configuration to block this feature?

What happens if you try to launch cmd.exe directly in your WSL shell?

**Comment by Dramelac** [comment]
@DrManhattanHack Is this problem still present? Have you found a solution?

**Comment by Dramelac** [comment]
I close the ticket for lack of information and unable to reproduce on our side.

If someone encounters this problem again, don't hesitate to reopen the ticket for a permanent fix.
