### ISSUE TITLE
Add feature: Exegol-version

### ISSUE THREAD

**Issue by 9426** [ShutdownRepo/Exegol#4]
Hi Shutdown,

It would be nice to be able to compare the local and the github version of Exegol to be sure to be up to date with a command like: "version".
Great tool by the way! ;)

**Comment by ShutdownRepo** [comment]
I finally found the way to do this :+1: 

This will be added in the next big release. Here, you have a preview of what it looks like, a Python wrapper to replace the actual Makefile in order to manager the container/image and such. You'll be able to call the wrapper with the positional argument `info` and it'll give you the following results.

![Screenshot from 2020-10-01 23-25-54](https://user-images.githubusercontent.com/40902872/94865224-840ea300-043d-11eb-958d-8b8cc0a6f63f.png)
